# Generated by Django 4.2.25 on 2025-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseChangeLog',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('date_executed', models.DateTimeField(verbose_name='Дата выполнения')),
                ('order_executed', models.IntegerField(verbose_name='Порядок выполнения')),
                ('exec_type', models.CharField(max_length=10, verbose_name='Тип выполнения')),
                ('md5sum', models.CharField(blank=True, max_length=35, null=True, verbose_name='MD5 сумма')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарии')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег')),
                ('liquibase', models.CharField(blank=True, max_length=20, null=True, verbose_name='Liquibase')),
                ('contexts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контексты')),
                ('labels', models.CharField(blank=True, max_length=255, null=True, verbose_name='Метки')),
                ('deployment_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID деплоя')),
            ],
            options={
                'verbose_name': 'Лог изменений БД',
                'verbose_name_plural': 'Логи изменений БД',
                'db_table': 'databasechangelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseChangeLogLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.IntegerField(verbose_name='Заблокировано')),
                ('lock_granted', models.DateTimeField(blank=True, null=True, verbose_name='Время блокировки')),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заблокировано кем')),
            ],
            options={
                'verbose_name': 'Блокировка лога БД',
                'verbose_name_plural': 'Блокировки логов БД',
                'db_table': 'databasechangeloglock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инвентарный номер')),
                ('serial_num', models.IntegerField(blank=True, null=True, verbose_name='Серийный номер')),
                ('id_directum_catalog', models.IntegerField(blank=True, null=True, verbose_name='ID Directum каталога')),
            ],
            options={
                'verbose_name': 'Экземпляр книги',
                'verbose_name_plural': 'Экземпляры книг',
                'db_table': 'dict_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор')),
                ('edition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Издание')),
                ('edition_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Информация об издании')),
                ('ph_property', models.CharField(blank=True, max_length=30, null=True, verbose_name='Физические свойства')),
                ('book_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер книги')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('id_directum', models.IntegerField(blank=True, null=True, verbose_name='ID Directum')),
            ],
            options={
                'verbose_name': 'Книга каталога',
                'verbose_name_plural': 'Книги каталога',
                'db_table': 'dict_catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictCatalogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.BinaryField(blank=True, null=True, verbose_name='Содержимое файла')),
            ],
            options={
                'verbose_name': 'Файл каталога',
                'verbose_name_plural': 'Файлы каталога',
                'db_table': 'dict_catalog_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_number', models.IntegerField(blank=True, null=True, verbose_name='Табельный номер')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('filial_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Филиал')),
                ('dept_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Отдел')),
                ('post_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Должность')),
                ('set_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата назначения')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'dict_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictOrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
                'db_table': 'dict_order_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'dict_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'db_table': 'dict_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'dict_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата')),
                ('fact_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('create_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Заказ книги',
                'verbose_name_plural': 'Заказы книг',
                'db_table': 'order_catalog',
                'managed': False,
            },
        ),
    ]
